from pydantic_settings import BaseSettings
from pathlib import Path
from typing import List

# Project root = two directories up from this file (backend/app/config.py)
_HERE = Path(__file__).resolve().parent          # backend/app/
_BACKEND_DIR = _HERE.parent                      # backend/
_PROJECT_ROOT = _BACKEND_DIR.parent              # project root


class Settings(BaseSettings):
    # ── Application ────────────────────────────────────────────
    APP_NAME: str = "TrafficVision AI"
    APP_VERSION: str = "2.0.0"
    DEBUG: bool = False

    # ── Database ───────────────────────────────────────────────
    # Default: SQLite in backend/data/ (no external DB required)
    DATABASE_URL: str = f"sqlite+aiosqlite:///{_BACKEND_DIR / 'data' / 'trafficvision.db'}"

    # ── Security / Auth ────────────────────────────────────────
    SECRET_KEY: str = "change-this-in-production-32chars"
    ALGORITHM: str = "HS256"
    ACCESS_TOKEN_EXPIRE_MINUTES: int = 1440  # 24 hours

    # Simple single-admin credentials (stored in env)
    ADMIN_USERNAME: str = "admin"
    ADMIN_PASSWORD: str = "admin123"
    ADMIN_NAME: str = "Traffic Officer"

    # ── File Storage ───────────────────────────────────────────
    UPLOAD_DIR: Path = _BACKEND_DIR / "data" / "uploads"
    EVIDENCE_DIR: Path = _BACKEND_DIR / "data" / "evidence"
    REPORTS_DIR: Path = _BACKEND_DIR / "data" / "reports"
    MODELS_DIR: Path = _BACKEND_DIR / "data" / "models"
    # Debug directory — plate crops saved here for diagnosis
    DEBUG_DIR: Path = _BACKEND_DIR / "data" / "uploads" / "debug"
    # Training evaluation directory (read by /api/v1/performance)
    TRAINING_EVAL_DIR: Path = _PROJECT_ROOT / "training" / "evaluation"

    # ── Upload limits ──────────────────────────────────────────
    MAX_IMAGE_SIZE_MB: int = 20
    ALLOWED_IMAGE_TYPES: List[str] = [
        "image/jpeg", "image/png", "image/webp",
        "image/bmp", "image/tiff",
    ]

    # ── YOLO Models — Base Fallback ─────────────────────────────
    # These are tried when custom-trained weights are absent
    YOLO_MODEL_NAME: str = "yolo11n.pt"
    YOLO_HELMET_MODEL_NAME: str = "helmet.pt"
    YOLO_PLATE_MODEL_NAME: str = "license_plate.pt"

    # ── YOLO Models — Custom Trained ────────────────────────────
    # Generated by train_vehicle.py / train_plate.py / train_helmet.py
    # These take highest priority when present.
    YOLO_VEHICLE_CUSTOM_MODEL: str = "trafficvision_vehicle.pt"
    YOLO_PLATE_CUSTOM_MODEL: str = "trafficvision_plate.pt"
    YOLO_HELMET_CUSTOM_MODEL: str = "trafficvision_helmet.pt"

    # ── YOLO Inference Thresholds ──────────────────────────────
    YOLO_CONFIDENCE_THRESHOLD: float = 0.35
    YOLO_IOU_THRESHOLD: float = 0.45
    YOLO_MAX_DETECTIONS: int = 100

    # ── OCR Configuration ──────────────────────────────────────
    # Primary engine: "paddleocr" (with EasyOCR fallback)
    # Set to "easyocr" to skip PaddleOCR and use EasyOCR directly.
    OCR_PRIMARY_ENGINE: str = "easyocr"
    OCR_LANGUAGES: List[str] = ["en"]

    # ── Image Preprocessing ────────────────────────────────────
    # Detect image conditions (low light, fog, rain, blur, noise)
    # and apply targeted corrections before YOLO inference.
    PREPROCESSING_DETECT_CONDITIONS: bool = True

    # ── CORS ───────────────────────────────────────────────────
    CORS_ORIGINS: List[str] = [
        "http://localhost:3000",
        "http://localhost:5173",
        "http://127.0.0.1:3000",
        "http://localhost:80",
        "http://localhost",
    ]

    model_config = {
        "env_file": str(_PROJECT_ROOT / ".env"),
        "env_file_encoding": "utf-8",
    }


settings = Settings()

# Expose project root for use by other modules (e.g. detection.py locating bundled weights)
PROJECT_ROOT = _PROJECT_ROOT

# Ensure directories exist at startup — resolve relative paths against project root
for _d in [
    settings.UPLOAD_DIR, settings.EVIDENCE_DIR,
    settings.REPORTS_DIR, settings.MODELS_DIR,
    settings.DEBUG_DIR,
]:
    Path(_d).resolve().mkdir(parents=True, exist_ok=True)

